"use client";

import { FormEvent, useState } from "react";
import { Check, Loader2, Mail, Palette, Radar } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function SettingsForm({ settings }: { settings: { brand_name: string; accent_color: string; report_footer: string; contact_email: string | null } }) {
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState<{ kind: "success" | "error"; text: string } | null>(null); const [brand, setBrand] = useState(settings.brand_name); const [color, setColor] = useState(settings.accent_color);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(null); const data = Object.fromEntries(new FormData(event.currentTarget).entries()); try { const response = await fetch("/api/settings", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(data) }); const payload = await response.json() as { error?: string }; if (!response.ok) throw new Error(payload.error || "Could not save settings."); setMessage({ kind: "success", text: "Report branding saved." }); } catch (error) { setMessage({ kind: "error", text: error instanceof Error ? error.message : "Could not save settings." }); } finally { setSaving(false); } }
  return <main className="mx-auto max-w-4xl p-5 sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.15em] text-teal-700">Workspace settings</p><h2 className="mt-2 text-3xl font-bold tracking-[-0.04em]">Client report branding</h2><p className="mt-2 text-sm leading-6 text-slate-500">These details appear on secure report links shared with your clients.</p><form onSubmit={submit} className="mt-8 rounded-2xl border bg-white p-6 shadow-sm sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">Brand name<Input name="brandName" className="mt-2" value={brand} onChange={(event) => setBrand(event.target.value)} required /></label><label className="text-sm font-semibold">Accent color<div className="relative mt-2"><Palette className="pointer-events-none absolute left-3.5 top-3.5 size-4 text-slate-400" /><Input name="accentColor" className="pl-10" value={color} onChange={(event) => setColor(event.target.value)} required pattern="#[0-9A-Fa-f]{6}" /></div></label><label className="text-sm font-semibold sm:col-span-2">Client contact email<div className="relative mt-2"><Mail className="pointer-events-none absolute left-3.5 top-3.5 size-4 text-slate-400" /><Input name="contactEmail" type="email" className="pl-10" defaultValue={settings.contact_email ?? ""} /></div></label><label className="text-sm font-semibold sm:col-span-2">Report footer<Input name="reportFooter" className="mt-2" defaultValue={settings.report_footer} maxLength={160} /></label></div><div className="mt-6 rounded-xl border bg-slate-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Preview</p><div className="mt-3 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl text-white" style={{ backgroundColor: /^#[0-9a-f]{6}$/i.test(color) ? color : "#0f766e" }}><Radar className="size-5" /></span><div><p className="text-sm font-bold">{brand || "Your agency"}</p><p className="text-[10px] uppercase tracking-wide text-slate-400">AI readiness report</p></div></div></div>{message ? <div className={`mt-5 flex items-center gap-2 rounded-xl border px-4 py-3 text-sm ${message.kind === "success" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-rose-200 bg-rose-50 text-rose-700"}`}>{message.kind === "success" ? <Check className="size-4" /> : null}{message.text}</div> : null}<div className="mt-7 flex justify-end"><Button type="submit" disabled={saving}>{saving ? <><Loader2 className="size-4 animate-spin" /> Saving</> : "Save branding"}</Button></div></form></main>;
}
