import { AlertTriangle, CheckCircle2, Clock3, FileText, Globe2 } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";

import { DashboardShell } from "@/components/dashboard-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { currentAccount } from "@/lib/auth";
import { query } from "@/lib/database";

interface ReportRow extends Record<string, unknown> { id: string; site_name: string; site_url: string; status: "running" | "completed" | "failed"; score: number | null; grade: string | null; error: string | null; started_at: string; completed_at: string | null; }

export default async function ReportsPage() {
  const account = await currentAccount(); if (!account) redirect("/login");
  const reports = await query<ReportRow>(`SELECT scans.id, scans.status, scans.score, scans.grade, scans.error, scans.started_at, scans.completed_at, sites.name AS site_name, sites.url AS site_url FROM scans JOIN sites ON sites.id = scans.site_id WHERE scans.organization_id = $1 ORDER BY scans.started_at DESC LIMIT 100`, [account.organization.id]);
  const completed = reports.filter((report) => report.status === "completed").length;
  return <DashboardShell account={account}><main className="mx-auto max-w-7xl p-5 sm:p-8"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-teal-700">Scan history</p><h2 className="mt-2 text-3xl font-bold tracking-[-0.04em]">Reports</h2><p className="mt-2 text-sm text-slate-500">Review every scan and reopen client-ready results.</p></div><div className="mt-8 grid gap-4 sm:grid-cols-3"><Summary label="Total scans" value={reports.length} icon={FileText} /><Summary label="Completed" value={completed} icon={CheckCircle2} /><Summary label="Needs attention" value={reports.length - completed} icon={AlertTriangle} /></div><section className="mt-6 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b px-5 py-4"><h3 className="text-sm font-bold">Recent reports</h3><p className="mt-1 text-xs text-slate-400">Up to 100 most recent scans</p></div>{reports.length ? <div className="divide-y">{reports.map((report) => <div key={report.id} className="grid gap-4 px-5 py-5 md:grid-cols-[1.35fr_.55fr_.65fr_auto] md:items-center"><div className="flex min-w-0 gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-600"><Globe2 className="size-4" /></span><div className="min-w-0"><p className="truncate text-sm font-bold">{report.site_name}</p><p className="mt-1 truncate text-xs text-slate-400">{report.site_url}</p>{report.error ? <p className="mt-1 truncate text-[10px] text-rose-600">{report.error}</p> : null}</div></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Status</p><Badge className="mt-1.5" variant={report.status === "completed" ? "success" : report.status === "failed" ? "warning" : "outline"}>{report.status}</Badge></div><div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Result</p><p className="mt-1 text-sm font-bold">{report.score === null ? "—" : `${report.score} · ${report.grade}`}</p><p className="mt-1 flex items-center gap-1 text-[10px] text-slate-400"><Clock3 className="size-3" />{new Date(report.started_at).toLocaleString()}</p></div><div className="md:text-right">{report.status === "completed" ? <Button size="sm" asChild><Link href={`/dashboard/reports/${report.id}`}>Open report</Link></Button> : <span className="text-xs text-slate-400">No report available</span>}</div></div>)}</div> : <div className="grid min-h-72 place-items-center p-8 text-center"><div><FileText className="mx-auto size-8 text-slate-300" /><p className="mt-3 text-sm font-bold">No reports yet</p><p className="mt-1 text-xs text-slate-400">Scan a client site to create the first report.</p><Button asChild className="mt-4"><Link href="/dashboard/sites">Choose a site</Link></Button></div></div>}</section></main></DashboardShell>;
}

function Summary({ label, value, icon: Icon }: { label: string; value: number; icon: typeof FileText }) { return <div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div><span className="grid size-10 place-items-center rounded-xl bg-slate-100 text-slate-600"><Icon className="size-5" /></span></div></div>; }
